name: debug_auto_complete
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  # https://pub.dev/packages/expandable
  expandable: 5.0.1

  # https://flutter.dev
  flutter:
    sdk: flutter

  # https://pub.dev/packages/flutter_fancy_tree_view
  # TODO(anyone): Update to 1.0.0
  flutter_fancy_tree_view: ^0.5.3+2

  # https://flutter.dev
  flutter_localizations:
    sdk: flutter

  # https://pub.dev/packages/folly_fields
  folly_fields: 0.20.5

  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: 10.4.0

  # https://pub.dev/packages/google_fonts
  google_fonts: 4.0.3

  # https://pub.dev/packages/http
  http: 0.13.5

  # https://pub.dev/packages/intl
  intl: ^0.17.0

  # https://pub.dev/packages/shared_preferences
  shared_preferences: 2.0.18

  # https://pub.dev/packages/url_launcher
  url_launcher: 6.1.10

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^2.0.0

  # https://flutter.dev
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
